name: Release

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize development environment
      run: npm install

    - name: Release package
      run: npm run release
      env:
        NPM_TOKEN: ${{ secrets.NPM_API_TOKEN }}
      if: ( github.event_name == 'release' && github.event.action == 'published' ) || github.event_name == 'workflow_dispatch'

    - name: Upload package
      run: |
        gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
        gh release upload ${{ github.event.release.tag_name }} build/*tgz --clobber
      if: ( github.event_name == 'release' && github.event.action == 'published' ) || github.event_name == 'workflow_dispatch'